export * from './cssSettings.service';
import { CssSettingsService } from './cssSettings.service';
export * from './environmentVariables.service';
import { EnvironmentVariablesService } from './environmentVariables.service';
export * from './files.service';
import { FilesService } from './files.service';
export * from './groupMembers.service';
import { GroupMembersService } from './groupMembers.service';
export * from './groups.service';
import { GroupsService } from './groups.service';
export * from './notifications.service';
import { NotificationsService } from './notifications.service';
export * from './permissions.service';
import { PermissionsService } from './permissions.service';
export * from './personalTokens.service';
import { PersonalTokensService } from './personalTokens.service';
export * from './processCategories.service';
import { ProcessCategoriesService } from './processCategories.service';
export * from './processRequests.service';
import { ProcessRequestsService } from './processRequests.service';
export * from './processes.service';
import { ProcessesService } from './processes.service';
export * from './rebuildScriptExecutors.service';
import { RebuildScriptExecutorsService } from './rebuildScriptExecutors.service';
export * from './requestFiles.service';
import { RequestFilesService } from './requestFiles.service';
export * from './screenCategories.service';
import { ScreenCategoriesService } from './screenCategories.service';
export * from './screens.service';
import { ScreensService } from './screens.service';
export * from './scriptCategories.service';
import { ScriptCategoriesService } from './scriptCategories.service';
export * from './scripts.service';
import { ScriptsService } from './scripts.service';
export * from './secuirtyLogs.service';
import { SecuirtyLogsService } from './secuirtyLogs.service';
export * from './settings.service';
import { SettingsService } from './settings.service';
export * from './signals.service';
import { SignalsService } from './signals.service';
export * from './taskAssignments.service';
import { TaskAssignmentsService } from './taskAssignments.service';
export * from './tasks.service';
import { TasksService } from './tasks.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [CssSettingsService, EnvironmentVariablesService, FilesService, GroupMembersService, GroupsService, NotificationsService, PermissionsService, PersonalTokensService, ProcessCategoriesService, ProcessRequestsService, ProcessesService, RebuildScriptExecutorsService, RequestFilesService, ScreenCategoriesService, ScreensService, ScriptCategoriesService, ScriptsService, SecuirtyLogsService, SettingsService, SignalsService, TaskAssignmentsService, TasksService, UsersService];
