/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AvailableGroupMembersAllOf } from './availableGroupMembersAllOf';


/**
 * Represents a group Members definition.
 */
export interface AvailableGroupMembers { 
    id?: string;
    description?: string;
    name?: string;
    status?: AvailableGroupMembers.StatusEnum;
    created_at?: string;
    updated_at?: string;
}
export namespace AvailableGroupMembers {
    export type StatusEnum = 'ACTIVE' | 'INACTIVE';
    export const StatusEnum = {
        Active: 'ACTIVE' as StatusEnum,
        Inactive: 'INACTIVE' as StatusEnum
    };
}


