/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommentsAllOf } from './commentsAllOf';
import { CommentsEditable } from './commentsEditable';


/**
 * Represents a business process definition.
 */
export interface Comments { 
    created_at?: string;
    updated_at?: string;
    id?: string;
    user_id?: string;
    commentable_id?: string;
    commentable_type?: string;
    up?: number;
    down?: number;
    subject?: string;
    body?: string;
    hidden?: boolean;
    type?: Comments.TypeEnum;
}
export namespace Comments {
    export type TypeEnum = 'LOG' | 'MESSAGE';
    export const TypeEnum = {
        Log: 'LOG' as TypeEnum,
        Message: 'MESSAGE' as TypeEnum
    };
}


