/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupMembersEditable } from './groupMembersEditable';
import { CreateGroupMembersAllOf } from './createGroupMembersAllOf';


export interface CreateGroupMembers { 
    id?: string;
    group?: object;
    member?: object;
    created_at?: string;
    updated_at?: string;
    group_id?: string;
    member_id?: string;
    member_type?: string;
    description?: string;
}

