/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InlineObject3 { 
    /**
     * list of message ids that will be marked as read
     */
    message_ids?: Array<string>;
    /**
     * all messages that has an url that is in this list will be marked as read
     */
    routes?: Array<string>;
}

