/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InlineObject5 { 
    /**
     * ID of the user whose permissions are configured
     */
    user_id?: number;
    /**
     * ID of the group whose permissions are configured
     */
    group_id?: number;
    /**
     * Whether the user should have Super Admin privileges
     */
    is_administrator?: boolean;
    permission_names?: Array<string>;
}

