/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Users } from './users';


export interface ProcessRequestAllOf { 
    id?: string;
    process_id?: string;
    process_collaboration_id?: string;
    participant_id?: string;
    process_category_id?: string;
    created_at?: string;
    updated_at?: string;
    user?: any | null;
    participants?: Array<Users>;
}

