/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProcessStartEvents } from './processStartEvents';
import { ProcessAllOf } from './processAllOf';
import { ProcessEditable } from './processEditable';


export interface Process { 
    user_id?: number;
    id?: string;
    deleted_at?: string;
    created_at?: string;
    updated_at?: string;
    notifications?: object;
    task_notifications?: object;
    process_category_id?: number;
    name?: string;
    description?: string;
    status?: Process.StatusEnum;
    pause_timer_start?: number;
    cancel_screen_id?: number;
    has_timer_start_events?: boolean;
    request_detail_screen_id?: number;
    is_valid?: number;
    package_key?: string;
    start_events?: Array<ProcessStartEvents>;
    warnings?: string;
    self_service_tasks?: object;
    signal_events?: Array<object>;
    category?: object;
    manager_id?: number;
}
export namespace Process {
    export type StatusEnum = 'ACTIVE' | 'INACTIVE' | 'ARCHIVED';
    export const StatusEnum = {
        Active: 'ACTIVE' as StatusEnum,
        Inactive: 'INACTIVE' as StatusEnum,
        Archived: 'ARCHIVED' as StatusEnum
    };
}


