/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProcessAllOf { 
    user_id?: number;
    id?: string;
    deleted_at?: string;
    created_at?: string;
    updated_at?: string;
    notifications?: object;
    task_notifications?: object;
}

