/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScreenTypeEditable } from './screenTypeEditable';
import { ScreenTypeAllOf } from './screenTypeAllOf';


/**
 * Represents a business screen Type definition.
 */
export interface ScreenType { 
    id?: string;
    name?: string;
}

