/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScreensEditable } from './screensEditable';
import { GroupMembersAllOf } from './groupMembersAllOf';


export interface Screens { 
    id?: string;
    created_at?: string;
    updated_at?: string;
    title?: string;
    type?: string;
    description?: string;
    config?: Array<object>;
    computed?: Array<object>;
    watchers?: Array<object>;
    custom_css?: string;
    screen_category_id?: string;
}

