/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScriptsEditable } from './scriptsEditable';
import { EnvironmentVariableAllOf } from './environmentVariableAllOf';


export interface Scripts { 
    id?: number;
    created_at?: string;
    updated_at?: string;
    title?: string;
    description?: string;
    language?: string;
    code?: string;
    timeout?: number;
    run_as_user_id?: number;
    key?: string;
    script_category_id?: number;
}

