/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SecurityLogOs } from './securityLogOs';


export interface SecurityLogMeta { 
    os?: Array<SecurityLogOs>;
    browser?: Array<SecurityLogOs>;
    user_agent?: string;
}

