/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SecurityLogMeta } from './securityLogMeta';


/**
 * Class SecurityLog
 */
export interface SecurityLog { 
    id?: number;
    event?: string;
    ip?: string;
    meta?: Array<SecurityLogMeta>;
    user_id?: number;
    occured_at?: string;
}

