/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SettingsEditable } from './settingsEditable';
import { GroupMembersAllOf } from './groupMembersAllOf';


/**
 * Class Settings
 */
export interface Settings { 
    id?: string;
    created_at?: string;
    updated_at?: string;
    key?: string;
    config?: Array<object>;
    name?: string;
    helper?: string;
    group?: string;
    format?: string;
    hidden?: boolean;
    readonly?: boolean;
    variables?: string;
    sansSerifFont?: string;
}

