/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SignalsEditable } from './signalsEditable';
import { SignalsAllOf } from './signalsAllOf';
import { SignalsAllOfProcesses } from './signalsAllOfProcesses';


/**
 * Represents a business signal definition.
 */
export interface Signals { 
    type?: string;
    processes?: Array<SignalsAllOfProcesses>;
    id?: string;
    name?: string;
    detail?: string;
}

