/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TokenClient { 
    id?: number;
    user_id?: number;
    name?: string;
    provider?: string;
    redirect?: string;
    personal_access_client?: boolean;
    password_client?: boolean;
    revoked?: boolean;
    created_at?: string;
    updated_at?: string;
}

