/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TokenClient } from './tokenClient';


export interface UserToken { 
    id?: string;
    user_id?: number;
    client_id?: number;
    name?: string;
    scopes?: object;
    revoked?: boolean;
    client?: TokenClient;
    created_at?: string;
    updated_at?: string;
    expires_at?: string;
}

